// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Umea.se.EstateService.DataStore;

#nullable disable

namespace Umea.se.EstateService.DataStore.Migrations
{
    [DbContext(typeof(EstateDbContext))]
    [Migration("20260218120000_BusinessTypeToOwnedType")]
    partial class BusinessTypeToOwnedType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Umea.se.EstateService.DataStore.Entities.BuildingAscendantDbEntity", b =>
                {
                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<double?>("EstateAscendantGeoLat")
                        .HasColumnType("float");

                    b.Property<double?>("EstateAscendantGeoLon")
                        .HasColumnType("float");

                    b.Property<int?>("EstateAscendantId")
                        .HasColumnType("int");

                    b.Property<string>("EstateAscendantName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EstateAscendantPopularName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("OrganizationAscendantGeoLat")
                        .HasColumnType("float");

                    b.Property<double?>("OrganizationAscendantGeoLon")
                        .HasColumnType("float");

                    b.Property<int?>("OrganizationAscendantId")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationAscendantName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrganizationAscendantPopularName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("RegionAscendantGeoLat")
                        .HasColumnType("float");

                    b.Property<double?>("RegionAscendantGeoLon")
                        .HasColumnType("float");

                    b.Property<int?>("RegionAscendantId")
                        .HasColumnType("int");

                    b.Property<string>("RegionAscendantName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RegionAscendantPopularName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("BuildingId");

                    b.ToTable("BuildingAscendants", (string)null);
                });

            modelBuilder.Entity("Umea.se.EstateService.DataStore.Entities.DataSyncMetadata", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("BuildingCount")
                        .HasColumnType("int");

                    b.Property<int>("EstateCount")
                        .HasColumnType("int");

                    b.Property<int>("FloorCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastRefreshUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RoomCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SyncMetadata", (string)null);
                });

            modelBuilder.Entity("Umea.se.EstateService.Shared.Data.Entities.BuildingEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool?>("BlueprintAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("BuildingCondition")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EstateId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalOwnerName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExternalOwnerNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExternalOwnerStatus")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("GrossArea")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ImageIds")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("ImageIds");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("NetArea")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("NumFloors")
                        .HasColumnType("int");

                    b.Property<int>("NumRooms")
                        .HasColumnType("int");

                    b.Property<string>("PopularName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PropertyDesignation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("YearOfConstruction")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EstateId");

                    b.HasIndex("Name");

                    b.HasIndex("Uid");

                    b.ToTable("Buildings", (string)null);
                });

            modelBuilder.Entity("Umea.se.EstateService.Shared.Data.Entities.EstateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AdministrativeArea")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("BuildingCount")
                        .HasColumnType("int");

                    b.Property<string>("ExternalOwnerName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExternalOwnerNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExternalOwnerStatus")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("GrossArea")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("MunicipalityArea")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("NetArea")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("OperationalArea")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PopularName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PropertyDesignation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Uid");

                    b.ToTable("Estates", (string)null);
                });

            modelBuilder.Entity("Umea.se.EstateService.Shared.Data.Entities.FloorEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<double?>("GrossArea")
                        .HasColumnType("float");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("NetArea")
                        .HasColumnType("float");

                    b.Property<string>("PopularName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("Uid");

                    b.ToTable("Floors", (string)null);
                });

            modelBuilder.Entity("Umea.se.EstateService.Shared.Data.Entities.RoomEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int?>("FloorId")
                        .HasColumnType("int");

                    b.Property<double>("GrossArea")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("NetArea")
                        .HasColumnType("float");

                    b.Property<string>("PopularName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("FloorId");

                    b.HasIndex("Uid");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("Umea.se.EstateService.Shared.Data.Entities.BuildingEntity", b =>
                {
                    b.OwnsOne("Umea.se.EstateService.Shared.Models.BusinessTypeModel", "BusinessType", b1 =>
                        {
                            b1.Property<int>("BuildingEntityId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("BusinessTypeId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("BusinessTypeName");

                            b1.HasKey("BuildingEntityId");

                            b1.ToTable("Buildings");

                            b1.WithOwner()
                                .HasForeignKey("BuildingEntityId");
                        });

                    b.OwnsOne("Umea.se.EstateService.Shared.ValueObjects.AddressModel", "Address", b1 =>
                        {
                            b1.Property<int>("BuildingEntityId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("AddressCity");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AddressCountry");

                            b1.Property<string>("Extra")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("AddressExtra");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("AddressStreet");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("AddressZipCode");

                            b1.HasKey("BuildingEntityId");

                            b1.ToTable("Buildings");

                            b1.WithOwner()
                                .HasForeignKey("BuildingEntityId");
                        });

                    b.OwnsOne("Umea.se.EstateService.Shared.ValueObjects.GeoPointModel", "GeoLocation", b1 =>
                        {
                            b1.Property<int>("BuildingEntityId")
                                .HasColumnType("int");

                            b1.Property<double>("Lat")
                                .HasColumnType("float")
                                .HasColumnName("GeoLocationLat");

                            b1.Property<double>("Lon")
                                .HasColumnType("float")
                                .HasColumnName("GeoLocationLon");

                            b1.HasKey("BuildingEntityId");

                            b1.ToTable("Buildings");

                            b1.WithOwner()
                                .HasForeignKey("BuildingEntityId");
                        });

                    b.OwnsOne("Umea.se.EstateService.Shared.Models.BuildingContactPersonsModel", "ContactPersons", b1 =>
                        {
                            b1.Property<int>("BuildingEntityId")
                                .HasColumnType("int");

                            b1.Property<string>("OperationCoordinator")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("OperationCoordinator");

                            b1.Property<string>("OperationsManager")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("OperationsManager");

                            b1.Property<string>("PropertyManager")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("PropertyManager");

                            b1.Property<string>("RentalAdministrator")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("RentalAdministrator");

                            b1.HasKey("BuildingEntityId");

                            b1.ToTable("Buildings");

                            b1.WithOwner()
                                .HasForeignKey("BuildingEntityId");
                        });

                    b.OwnsOne("Umea.se.EstateService.Shared.Models.BuildingNoticeBoardModel", "NoticeBoard", b1 =>
                        {
                            b1.Property<int>("BuildingEntityId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("EndDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("NoticeBoardEndDate");

                            b1.Property<DateTime?>("StartDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("NoticeBoardStartDate");

                            b1.Property<string>("Text")
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("NoticeBoardText");

                            b1.HasKey("BuildingEntityId");

                            b1.ToTable("Buildings");

                            b1.WithOwner()
                                .HasForeignKey("BuildingEntityId");
                        });

                    b.Navigation("Address");

                    b.Navigation("BusinessType");

                    b.Navigation("ContactPersons");

                    b.Navigation("GeoLocation");

                    b.Navigation("NoticeBoard");
                });

            modelBuilder.Entity("Umea.se.EstateService.Shared.Data.Entities.EstateEntity", b =>
                {
                    b.OwnsOne("Umea.se.EstateService.Shared.ValueObjects.AddressModel", "Address", b1 =>
                        {
                            b1.Property<int>("EstateEntityId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("AddressCity");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AddressCountry");

                            b1.Property<string>("Extra")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("AddressExtra");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("AddressStreet");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("AddressZipCode");

                            b1.HasKey("EstateEntityId");

                            b1.ToTable("Estates");

                            b1.WithOwner()
                                .HasForeignKey("EstateEntityId");
                        });

                    b.OwnsOne("Umea.se.EstateService.Shared.ValueObjects.GeoPointModel", "GeoLocation", b1 =>
                        {
                            b1.Property<int>("EstateEntityId")
                                .HasColumnType("int");

                            b1.Property<double>("Lat")
                                .HasColumnType("float")
                                .HasColumnName("GeoLocationLat");

                            b1.Property<double>("Lon")
                                .HasColumnType("float")
                                .HasColumnName("GeoLocationLon");

                            b1.HasKey("EstateEntityId");

                            b1.ToTable("Estates");

                            b1.WithOwner()
                                .HasForeignKey("EstateEntityId");
                        });

                    b.Navigation("Address");

                    b.Navigation("GeoLocation");
                });
#pragma warning restore 612, 618
        }
    }
}
