// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Umea.se.EstateService.DataStore;

#nullable disable

namespace Umea.se.EstateService.DataStore.Migrations
{
    [DbContext(typeof(EstateDbContext))]
    [Migration("20260320144826_AddWorkOrderTypes")]
    partial class AddWorkOrderTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Umea.se.EstateService.DataStore.Entities.BuildingAscendantDbEntity", b =>
                {
                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EstateAscendantGeoLat")
                        .HasColumnType("REAL");

                    b.Property<double?>("EstateAscendantGeoLon")
                        .HasColumnType("REAL");

                    b.Property<int?>("EstateAscendantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EstateAscendantName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EstateAscendantPopularName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("OrganizationAscendantGeoLat")
                        .HasColumnType("REAL");

                    b.Property<double?>("OrganizationAscendantGeoLon")
                        .HasColumnType("REAL");

                    b.Property<int?>("OrganizationAscendantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrganizationAscendantName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationAscendantPopularName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("RegionAscendantGeoLat")
                        .HasColumnType("REAL");

                    b.Property<double?>("RegionAscendantGeoLon")
                        .HasColumnType("REAL");

                    b.Property<int?>("RegionAscendantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegionAscendantName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionAscendantPopularName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("BuildingId");

                    b.ToTable("BuildingAscendants", (string)null);
                });

            modelBuilder.Entity("Umea.se.EstateService.DataStore.Entities.DataSyncMetadata", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstateCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FloorCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastRefreshUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkOrderCategoriesJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SyncMetadata", (string)null);
                });

            modelBuilder.Entity("Umea.se.EstateService.Shared.Data.Entities.BuildingEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BackgroundCacheFetchedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BackgroundCacheFetchedAtUtc");

                    b.Property<bool?>("BlueprintAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuildingCondition")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalOwnerName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalOwnerNote")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalOwnerStatus")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossArea")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageIds")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageIds");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetArea")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumDocuments")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumDocuments");

                    b.Property<int>("NumFloors")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumRooms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PopularName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyDesignation")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkOrderTypes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("WorkOrderTypes");

                    b.Property<string>("YearOfConstruction")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EstateId");

                    b.HasIndex("Name");

                    b.HasIndex("Uid");

                    b.ToTable("Buildings", (string)null);
                });

            modelBuilder.Entity("Umea.se.EstateService.Shared.Data.Entities.EstateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdministrativeArea")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("BuildingCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalOwnerName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalOwnerNote")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalOwnerStatus")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossArea")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("MunicipalityArea")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetArea")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationalArea")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PopularName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyDesignation")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Uid");

                    b.ToTable("Estates", (string)null);
                });

            modelBuilder.Entity("Umea.se.EstateService.Shared.Data.Entities.FavoriteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail");

                    b.HasIndex("UserEmail", "NodeType", "NodeId")
                        .IsUnique();

                    b.ToTable("Favorites", null, t =>
                        {
                            t.HasCheckConstraint("CK_Favorites_NodeType", "[NodeType] IN ('Estate', 'Building', 'Room')");
                        });
                });

            modelBuilder.Entity("Umea.se.EstateService.Shared.Data.Entities.FloorEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("GrossArea")
                        .HasColumnType("REAL");

                    b.Property<double?>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("NetArea")
                        .HasColumnType("REAL");

                    b.Property<string>("PopularName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("Uid");

                    b.ToTable("Floors", (string)null);
                });

            modelBuilder.Entity("Umea.se.EstateService.Shared.Data.Entities.RoomEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FloorId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GrossArea")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("NetArea")
                        .HasColumnType("REAL");

                    b.Property<string>("PopularName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("FloorId");

                    b.HasIndex("Uid");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("Umea.se.EstateService.Shared.Data.Entities.WorkOrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedByEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long?>("NextSyncAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotifierEmail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotifierName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PythagorasStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PythagorasStatusName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PythagorasWorkOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SubmittedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("SyncStatus");

                    b.Property<Guid>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkOrderTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("NextSyncAt");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("Uid");

                    b.ToTable("WorkOrders", (string)null);
                });

            modelBuilder.Entity("Umea.se.EstateService.Shared.Data.Entities.WorkOrderFileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Uploaded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkOrderFiles", (string)null);
                });

            modelBuilder.Entity("Umea.se.EstateService.Shared.Data.Entities.BuildingEntity", b =>
                {
                    b.OwnsOne("Umea.se.EstateService.Shared.ValueObjects.AddressModel", "Address", b1 =>
                        {
                            b1.Property<int>("BuildingEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("AddressCity");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("AddressCountry");

                            b1.Property<string>("Extra")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("AddressExtra");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("AddressStreet");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("AddressZipCode");

                            b1.HasKey("BuildingEntityId");

                            b1.ToTable("Buildings");

                            b1.WithOwner()
                                .HasForeignKey("BuildingEntityId");
                        });

                    b.OwnsOne("Umea.se.EstateService.Shared.ValueObjects.GeoPointModel", "GeoLocation", b1 =>
                        {
                            b1.Property<int>("BuildingEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("Lat")
                                .HasColumnType("REAL")
                                .HasColumnName("GeoLocationLat");

                            b1.Property<double>("Lon")
                                .HasColumnType("REAL")
                                .HasColumnName("GeoLocationLon");

                            b1.HasKey("BuildingEntityId");

                            b1.ToTable("Buildings");

                            b1.WithOwner()
                                .HasForeignKey("BuildingEntityId");
                        });

                    b.OwnsOne("Umea.se.EstateService.Shared.Models.BuildingContactPersonsModel", "ContactPersons", b1 =>
                        {
                            b1.Property<int>("BuildingEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("OperationCoordinator")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("OperationCoordinator");

                            b1.Property<string>("OperationsManager")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("OperationsManager");

                            b1.Property<string>("PropertyManager")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("PropertyManager");

                            b1.Property<string>("RentalAdministrator")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("RentalAdministrator");

                            b1.HasKey("BuildingEntityId");

                            b1.ToTable("Buildings");

                            b1.WithOwner()
                                .HasForeignKey("BuildingEntityId");
                        });

                    b.OwnsOne("Umea.se.EstateService.Shared.Models.BuildingNoticeBoardModel", "NoticeBoard", b1 =>
                        {
                            b1.Property<int>("BuildingEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime?>("EndDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("NoticeBoardEndDate");

                            b1.Property<DateTime?>("StartDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("NoticeBoardStartDate");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("TEXT")
                                .HasColumnName("NoticeBoardText");

                            b1.HasKey("BuildingEntityId");

                            b1.ToTable("Buildings");

                            b1.WithOwner()
                                .HasForeignKey("BuildingEntityId");
                        });

                    b.OwnsOne("Umea.se.EstateService.Shared.Models.BusinessTypeModel", "BusinessType", b1 =>
                        {
                            b1.Property<int>("BuildingEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BusinessTypeId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("BusinessTypeName");

                            b1.HasKey("BuildingEntityId");

                            b1.ToTable("Buildings");

                            b1.WithOwner()
                                .HasForeignKey("BuildingEntityId");
                        });

                    b.Navigation("Address");

                    b.Navigation("BusinessType");

                    b.Navigation("ContactPersons");

                    b.Navigation("GeoLocation");

                    b.Navigation("NoticeBoard");
                });

            modelBuilder.Entity("Umea.se.EstateService.Shared.Data.Entities.EstateEntity", b =>
                {
                    b.OwnsOne("Umea.se.EstateService.Shared.ValueObjects.AddressModel", "Address", b1 =>
                        {
                            b1.Property<int>("EstateEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("AddressCity");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("AddressCountry");

                            b1.Property<string>("Extra")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("AddressExtra");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("AddressStreet");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("AddressZipCode");

                            b1.HasKey("EstateEntityId");

                            b1.ToTable("Estates");

                            b1.WithOwner()
                                .HasForeignKey("EstateEntityId");
                        });

                    b.OwnsOne("Umea.se.EstateService.Shared.ValueObjects.GeoPointModel", "GeoLocation", b1 =>
                        {
                            b1.Property<int>("EstateEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("Lat")
                                .HasColumnType("REAL")
                                .HasColumnName("GeoLocationLat");

                            b1.Property<double>("Lon")
                                .HasColumnType("REAL")
                                .HasColumnName("GeoLocationLon");

                            b1.HasKey("EstateEntityId");

                            b1.ToTable("Estates");

                            b1.WithOwner()
                                .HasForeignKey("EstateEntityId");
                        });

                    b.Navigation("Address");

                    b.Navigation("GeoLocation");
                });

            modelBuilder.Entity("Umea.se.EstateService.Shared.Data.Entities.WorkOrderFileEntity", b =>
                {
                    b.HasOne("Umea.se.EstateService.Shared.Data.Entities.WorkOrderEntity", "WorkOrder")
                        .WithMany("Files")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Umea.se.EstateService.Shared.Data.Entities.WorkOrderEntity", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
