name: $(buildName)_$(Date:yyyy-MM-ddTHH.mm.ss)

# This pipeline is triggered by DevOps Build Validation feature
# Project Settings > Repositories > [repo] > Policies > [branch] > Build Validation
pr:
  branches:
    include:
      - kv/14992-autoreleasepipeline #TODO: set to main when done testing

trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: git
      name: Turkos/ume-pipeline-templates
      ref: refs/tags/release/v251002T1332-14281

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: prod
    values:
      - prod

variables:
  - template: pipelines/general/template-default-pipeline-variables.yml@templates
    parameters:
      environment: ${{ parameters.environment }}

stages:
  - stage: CheckForChangesStage
    displayName: Check for changes
    condition: eq(variables['Build.Reason'], 'PullRequest')
    jobs:
      - template: pipelines/general/template-check-for-changes.yml@templates
        parameters:
          comparisonBranch: origin/$(System.PullRequest.TargetBranchName)
          paths:
            - src/ume-app-estateservice

  # Estateservice API
  - stage: BuildEstateServiceStage
    displayName: Build EstateService
    dependsOn: CheckForChangesStage
    variables:
      changedPaths: $[ dependencies.CheckForChangesStage.outputs['Job.Task.CHANGED_PATHS'] ]
    condition: >-
      and(
        not(or(failed(), canceled())),
        contains(variables['changedPaths'], 'ume-app-estateservice')
      )
    jobs:
      - template: pipelines/azure/template-build-backend.yml@templates
        parameters:
          projectFolderName: ume-app-estateservice
          entrypointProjectName: Umea.se.EstateService.API
          shouldPublish: false
  # ------