using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Net.Http.Headers;
using Swashbuckle.AspNetCore.Annotations;
using Umea.se.EstateService.API.Controllers.Requests;
using Umea.se.EstateService.Logic.Exceptions;
using Umea.se.EstateService.Logic.Interfaces;
using Umea.se.EstateService.Logic.Models;
using Umea.se.EstateService.Shared.Models;

namespace Umea.se.EstateService.API.Controllers;

[ApiController]
[Produces("application/json")]
[Route(ApiRoutes.Floors)]
[Authorize]
public sealed class FloorController(
    IFloorBlueprintService blueprintService,
    IPythagorasHandler pythagorasHandler,
    ILogger<FloorController> logger) : ControllerBase
{
    private readonly IFloorBlueprintService _blueprintService = blueprintService;
    private readonly IPythagorasHandler _pythagorasHandler = pythagorasHandler;
    private readonly ILogger<FloorController> _logger = logger;

    /// <summary>
    /// Retrieves metadata for a specific floor.
    /// </summary>
    /// <param name="floorId">The floor identifier.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The requested floor metadata.</returns>
    [HttpGet("{floorId:int}")]
    [SwaggerOperation(
        Summary = "Get floor",
        Description = "Retrieves metadata for a floor using the floorIds[] filter."
    )]
    [SwaggerResponse(StatusCodes.Status200OK, "Floor metadata", typeof(FloorInfoModel))]
    [SwaggerResponse(StatusCodes.Status404NotFound, "Floor not found.")]
    public async Task<ActionResult<FloorInfoModel>> GetFloorAsync(
        int floorId,
        CancellationToken cancellationToken)
    {
        IReadOnlyList<FloorInfoModel> floors = await _pythagorasHandler
            .GetFloorsAsync([floorId], queryArgs: null, cancellationToken)
            .ConfigureAwait(false);

        if (floors.Count == 0)
        {
            return NotFound();
        }

        return Ok(floors[0]);
    }

    /// <summary>
    /// Retrieves a floor blueprint in PDF or SVG format.
    /// </summary>
    /// <remarks>
    /// Streams the floor blueprint generated by Pythagoras.
    /// </remarks>
    /// <param name="floorId">The floor identifier.</param>
    /// <param name="request">Blueprint request parameters.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    [HttpGet("{floorId:int}/blueprint")]
    [SwaggerOperation(
        Summary = "Get floor blueprint",
        Description = "Streams a floor blueprint as PDF or SVG."
    )]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status409Conflict)]
    [ProducesResponseType(StatusCodes.Status502BadGateway)]
    public async Task<IActionResult> GetFloorBlueprintAsync(
        int floorId,
        [FromQuery] FloorBlueprintRequest request,
        CancellationToken cancellationToken)
    {
        if (!ModelState.IsValid)
        {
            ValidationProblemDetails validationProblem = new(ModelState)
            {
                Status = StatusCodes.Status400BadRequest
            };

            return BadRequest(validationProblem);
        }

        try
        {
            FloorBlueprint blueprint = await _blueprintService.GetBlueprintAsync(floorId, request.Format, request.IncludeWorkspaceTexts, cancellationToken).ConfigureAwait(false);
            blueprint.Content.Position = 0;

            Response.GetTypedHeaders().CacheControl = new CacheControlHeaderValue
            {
                Public = true,
                MaxAge = TimeSpan.FromHours(24)
            };

            return File(blueprint.Content, blueprint.ContentType, blueprint.FileName);
        }
        catch (FloorBlueprintValidationException ex)
        {
            _logger.LogWarning(ex, "Validation error while generating blueprint for floor {FloorId}", floorId);
            ProblemDetails problem = new()
            {
                Status = StatusCodes.Status400BadRequest,
                Title = "Invalid blueprint request",
                Detail = ex.Message
            };

            return BadRequest(problem);
        }
        catch (FloorBlueprintUnavailableException ex)
        {
            _logger.LogError(ex, "Blueprint unavailable for floor {FloorId}", floorId);
            ProblemDetails problem = new()
            {
                Status = StatusCodes.Status502BadGateway,
                Title = "Blueprint unavailable",
                Detail = ex.Message
            };

            return StatusCode(StatusCodes.Status502BadGateway, problem);
        }
        catch (KeyNotFoundException ex)
        {
            _logger.LogWarning(ex, "Floor {FloorId} not found when requesting blueprint", floorId);
            ProblemDetails problem = new()
            {
                Status = StatusCodes.Status404NotFound,
                Title = "Floor not found",
                Detail = "The requested floor could not be located."
            };

            return NotFound(problem);
        }
        catch (InvalidOperationException ex)
        {
            _logger.LogWarning(ex, "Conflict while generating blueprint for floor {FloorId}", floorId);
            ProblemDetails problem = new()
            {
                Status = StatusCodes.Status409Conflict,
                Title = "Blueprint generation conflict",
                Detail = ex.Message
            };

            return Conflict(problem);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Unexpected error while generating blueprint for floor {FloorId}", floorId);
            ProblemDetails problem = new()
            {
                Status = StatusCodes.Status500InternalServerError,
                Title = "Blueprint generation failed",
                Detail = "Unexpected error while generating blueprint."
            };

            return StatusCode(StatusCodes.Status500InternalServerError, problem);
        }
    }
}
